### ISSUE TITLE
Key definitions is not required at default

### ISSUE THREAD

**Issue by ukstv** [seanohalpin/ffi-ncurses#3]
It seems keydefs.rb is never used or required so things like FFI::NCurses::KEY_UP or FFI::NCurses::KEY_DOWN raise error.

**Comment by seanohalpin** [comment]
You can require it yourself using 'require "ffi-ncurses/keydefs.rb"' or install the latest version of the gem (0.3.3) where it is done for you.

**Comment by ukstv** [comment]
Thanks!
