### ISSUE TITLE
Incompatible with rubinius1.0-rc3

### ISSUE THREAD

**Issue by ukstv** [seanohalpin/ffi-ncurses#4]
Or rubinius is not so mature, I can't say precisely. It raises such cryptic error:
    no method '+' on _pad_x:Symbol. (NoMethodError)
at /ffi-ncurses-0.3.2/lib/ffi-ncurses/winstruct.rb:29

**Comment by seanohalpin** [comment]
Yup. It pains me too. The rubinius FFI is not as advanced as the Ruby one (ironic as it is the original). I'll be looking into it shortly.
