### ISSUE TITLE
using REE with ubuntu-10.04 ffi-ncurses requires "libXCurses.so"

### ISSUE THREAD

**Issue by fpauser** [seanohalpin/ffi-ncurses#6]
see the gist: http://gist.github.com/458420

**Comment by fpauser** [comment]
To work around this one can set the ENV-Variable "RUBY_FFI_NCURSES_LIB" so it points to the actual ncurses-lib: export RUBY_FFI_NCURSES_LIB="libncurses.so.5"

see: http://github.com/seanohalpin/ffi-ncurses/blob/master/lib/ffi-ncurses.rb

**Comment by seanohalpin** [comment]
This is fixed in the latest version (0.3.3).
